on:
  push:
    branches:
      - main
      
name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git tag -s -a test -m "test"
        git push origin test
